Dev. checkpoint.

diff --git a/sv/nhk_record_newsline/run b/sv/nhk_record_newsline/run
--- a/sv/nhk_record_newsline/run
+++ b/sv/nhk_record_newsline/run
@@ -2,9 +2,15 @@
 #
 #
 
-set -u -e -o pipefail
+set -u -e # -o pipefail
 PATH="$PATH:/apps/my_nhk/bin"
-while : ; do
-  my_nhk record-next "NEWSLINE" || :
-  sleep "$(( 60 * 60 * 12 ))"
-done
+mkdir -p /tmp/nhk
+NHK_LOG=/tmp/nhk/record-newsline
+
+case "$(date +"%I:%M")" in
+  "05:59"|"11:59")
+    echo -n "--- Beginning to record @ "
+    date +"%H:%M:%S"
+    my_nhk record-next "NEWSLINE" || echo "error $?"
+    ;;
+esac
